import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import "./home.css";

const geistSans = localFont({
  src: "../fonts/Universal-Sans-Display-350.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>{children}</body>
    </html>
  );
}
